
mqtt_address: "mqtt.innok-robotics.de"
mqtt_port: 1883
mqtt_username: "thomas"
mqtt_password: "pheoriehoh9R"
manufacturer_name: "Innok_Robotics"
serial_number: "induros240001"
robot_name: "induros240001"
vda5050_major_version: "v2"
protocol_version: "2.0.0"